---
title: "Parkinson"
author: "Jinman Rong"
date: "6/18/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(dplyr)
library(tidyverse)
library(foreign)
library(scales)
library(ggplot2)
```

# RXQ_RX_I
```{r}
RXQ_RX_I = read.xport("/Users/jemma/Downloads/RXQ_RX_I.XPT")
head(RXQ_RX_I)
```
## Filter Parkinson's disease: G20
```{r}
#RXQ_RX_I_patients <- RXQ_RX_I %>% filter(RXDRSC1 == "G20" | RXDRSC2 == "G20" | RXDRSC2 == "G20")
RXQ_RX_I_needed <- RXQ_RX_I %>% select("SEQN", "RXDRSC1", "RXDRSC2", "RXDRSC3")
```

## Demographics: Gender, Race and Age
```{r}
DEMO_I = read.xport("/Users/jemma/Downloads/DEMO_I.XPT") 
DEMO_I_needed <- DEMO_I %>% select("SEQN", "RIAGENDR", "RIDRETH3","RIDAGEYR") %>% drop_na()

# transfer to dummies
DEMO_I_needed$RIAGENDR = case_when(DEMO_I_needed$RIAGENDR==1~1, DEMO_I_needed$RIAGENDR==2~0)
DEMO_I_needed$RIAGENDR = as.factor(DEMO_I_needed$RIAGENDR)

DEMO_I_needed <- fastDummies::dummy_cols(DEMO_I_needed, select_columns = "RIDRETH3")
DEMO_I_needed_final <- DEMO_I_needed %>% select(-"RIDRETH3")

# rescale continuous variable
#DEMO_I_needed_final <- DEMO_I_needed_final %>% mutate(rescaled_age = rescale(DEMO_I_needed_final$RIDAGEYR)) %>% select(-"RIDAGEYR")
head(DEMO_I_needed_final)
```

## Depression & Sleepless & Fatigue
```{r}
DPQ_I = read.xport("/Users/jemma/Downloads/DPQ_I.XPT")
head(DPQ_I)
```

```{r}
DPQ_I_needed <- DPQ_I %>% filter(DPQ020 == 0 | DPQ020 == 1 | DPQ020 == 2 | DPQ020 == 3) %>% filter(DPQ090 == 0 | DPQ090 == 1 | DPQ090 == 2 | DPQ090 == 3) %>% filter(DPQ100 == 0 | DPQ100 == 1 | DPQ100 == 2 | DPQ100 == 3) %>% filter(DPQ030 == 0 | DPQ030 == 1 | DPQ030 == 2 | DPQ030 == 3) %>% filter(DPQ040 == 0 | DPQ040 == 1 | DPQ040 == 2 | DPQ040 == 3) %>% select("SEQN", "DPQ020", "DPQ090", "DPQ100", "DPQ030","DPQ040") %>% drop_na()

# transfer to dummies
DPQ_I_needed_2 <- fastDummies::dummy_cols(DPQ_I_needed, select_columns = c("DPQ020", "DPQ090", "DPQ100", "DPQ030","DPQ040"))
DPQ_I_needed_final <- DPQ_I_needed_2 %>% select(-"DPQ020", -"DPQ090", -"DPQ100", -"DPQ030",-"DPQ040")
```

## Sleepless
```{r}
SLQ_I = read.xport("/Users/jemma/Downloads/SLQ_I.XPT")
SLQ_I_needed <- SLQ_I %>% filter(SLQ050 ==1 | SLQ050 ==2) %>% select("SEQN", "SLQ050") %>% drop_na()
SLQ_I_needed$SLQ050 = case_when(SLQ_I_needed$SLQ050==1~1, SLQ_I_needed$SLQ050==2~0)
SLQ_I_needed$SLQ050 = as.factor(SLQ_I_needed$SLQ050)

```

## Physical Functioning
```{r}
PFQ_I = read.xport("/Users/jemma/Downloads/PFQ_I.XPT")
PFQ_I_needed <- PFQ_I %>% filter(PFQ_I$PFQ061C ==1 | PFQ_I$PFQ061C ==2 | PFQ_I$PFQ061C == 3 | PFQ_I$PFQ061C == 4) %>% select("SEQN", "PFQ061C") %>% drop_na()
# transfer to dummies
PFQ_I_needed_2 <- fastDummies::dummy_cols(PFQ_I_needed, select_columns = "PFQ061C") %>% select(-"PFQ061C")
```

## Join tables
```{r}
table_all_I = Reduce(function(x,y) merge(x = x, y = y, by = "SEQN"), 
       list(RXQ_RX_I_needed, DEMO_I_needed_final, PFQ_I_needed_2, SLQ_I_needed,DPQ_I_needed_final))
table_all_I_final <- table_all_I %>% mutate(rescaled_age = rescale(table_all_I$RIDAGEYR)) %>% select(-"RIDAGEYR")
table_all_I_final <- table_all_I_final %>% mutate(Parkinson = case_when((RXDRSC1 == "G20" | RXDRSC2 == "G20" | RXDRSC2 == "G20")~1,(RXDRSC1 != "G20" & RXDRSC2 != "G20" & RXDRSC2 != "G20")~0))
table_all_I_final$Parkinson = as.factor(table_all_I_final$Parkinson)
table_all_I_final <- table_all_I_final %>% select(-"RXDRSC1",-"RXDRSC2",-"RXDRSC3")
#nrow(table_all_I)
#head(table_all_I)
```

```{r}
colnames(table_all_I_final) = c("SEQN", "Gender","Non-Hispanic White","Non-Hispanic Black", "Mexican American", "Other Hispanic", "Non-Hispanic Asian", "Other Race - Including Multi-Racial", "Walking up ten steps_Some difficulty", "Walking up ten steps_No difficulty", "Walking up ten steps_Unable to do", "Walking up ten steps_Much difficulty", "Sleepless", "Feeling down, depressed, or hopeless_Not at all", "Feeling down, depressed, or hopeless_Several days", "Feeling down, depressed, or hopeless_More than half of the days", "Feeling down, depressed, or hopeless_Nearly every day", "Thought you would be better off dead_Not at all", "Thought you would be better off dead_Several days", "Thought you would be better off dead_Nearly every day", "Thought you would be better off dead_More than half the days", "Difficulty these problems have caused_Not at all difficult", " Difficulty these problems have caused_Somewhat difficult", " Difficulty these problems have caused_Very difficult", "Difficulty these problems have caused_Extremely difficult", "Trouble sleeping or sleeping too much_Not at all", "Trouble sleeping or sleeping too much_More than half the days", "Trouble sleeping or sleeping too much_Several days", "Trouble sleeping or sleeping too much_Nearly every day", "Feeling tired or having little energy_Several days", "Feeling tired or having little energy_Not at all", "Feeling tired or having little energy_More than half the days","Feeling tired or having little energy_Nearly every day", "Rescaled_age", "Parkinson")
```

```{r}
head(table_all_I_final)
```

```{r}
write_csv(table_all_I_final, "table_Parkinson.csv")
```